version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/dashedboard
  build-machine:
    docker:
      - image: circleci/node:12
    working_directory: ~/dashedboard

  big-machine:
    docker:
      - image: circleci/node:12
    working_directory: ~/dashedboard

  super-machine:
    docker:
      - image: circleci/node:10
    working_directory: ~/dashedboard

  giant-machine:
    docker:
      - image: circleci/node:12
    working_directory: ~/dashedboard

  exec-defaults:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/dashedboard

jobs:
  build:
    executor: node

    working_directory: ~/dashedboard

    steps:
      - checkout
      - run: npm install
      - run: npm run build
  test:
    executor: node

    working_directory: ~/dashedboard

    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm test

  buildAgain:
    executor: big-machine

    working_directory: ~/dashedboard
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: rm -r dist
      - checkout
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: rm -r dist
      - checkout
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: rm -r dist
      - checkout
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: rm -r dist
      - checkout
      - run: npm install
      - run: npm run build

  builder:
    executor: super-machine

    working_directory: ~/dashedboard
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: rm -r dist
      - checkout
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: rm -r dist
      - checkout
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: rm -r dist
      - checkout
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: rm -r dist
      - checkout
      - run: npm install
      - run: npm run build
  worker:
    executor: giant-machine

    working_directory: ~/dashedboard
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: rm -r dist
      - checkout
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: rm -r dist
      - checkout
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: rm -r dist
      - checkout
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: rm -r dist
      - checkout
      - run: npm install
      - run: npm run build

workflows:
  version: 2
  hourly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - "master"
                - "update"
    jobs:
      - "test"
      - "build"
      - "test"
      - "buildAgain"
      - "builder"
      - "worker"
  build:
    jobs:
      - "test"
      - "build"
      - "buildAgain"
      - "builder"
      - "worker"
